all: matrprimos ejer1 taylor ejer2

matrprimos: matrprimos.c
	gcc -o matrprimos matrprimos.c -lm

ejer1: ejer1.c
	gcc -o ejer1 ejer1.c -lm -lpthread

taylor: taylor.c
	gcc -o taylor taylor.c -lm -lpthread

ejer2: ejer2.c
	gcc -o ejer2 ejer2.c -lm -lpthread

clean:
	rm matrprimos
